packages:
  dealii:
    require: ~examples +simplex ~nanoflann ~gmsh ~python
  hdf5:
    require: +fortran +cxx +hl
  petsc:
    require: +mumps +suite-sparse +p4est
  cgns:
    require: +fortran
  trilinos:
    require: +rol +mesquite +mumps +suite-sparse +superlu-dist
  libmesh:
    require: +boost +eigen +fparser +hdf5 +laspack +metis +perflog +petsc 
             +slepc +tetgen +triangle
  vtk:
    require: +python
  all:
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
